# Generated by Django 5.0.2 on 2024-03-05 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_app", "0002_alter_product_options_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name_plural": "Order"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name_plural": "Product"},
        ),
    ]
